export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

export const PRODUCTS_ADD_ITEM = "PRODUCTS_ADD_ITEM";
export const PRODUCTS_REMOVE_ITEM = "PRODUCTS_REMOVE_ITEM";
export const PRODUCTS_CLEAR_ITEMS = "PRODUCTS_CLEAR_ITEMS";
